name: Publish Executables

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      
jobs:
  build-api:
    name: "Build Artifacts"
    runs-on: ubuntu-latest
    steps:

      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Import GPG key
        id: import_gpg
        uses: paultyng/ghaction-import-gpg@v2.1.0
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}

      - uses: actions/checkout@v2
      - run: npm ci install
      - run: make all

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
      
      - uses: AButler/upload-release-assets@v2.0
        with:
          files: 'artifacts/*'
          release-tag: ${{ github.ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}